# Generated by Django 5.2.5 on 2025-11-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('reception', 'Reception'), ('doctor', 'Doctor'), ('laboratory', 'Laboratory'), ('staff', 'Staff'), ('admin', 'Admin')], default='patient', max_length=20),
        ),
    ]
