"""
Django settings for university_api project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from datetime import timedelta
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-yt)2uovn6ck=nwxdrvh#^jr7@o1wrsg%&&!cmp(gxn%f==hl+y')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Use environment variables for allowed hosts
ALLOWED_HOSTS_str = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,uni-find-api.onrender.com')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_str.split(',')]

# Ensure Render domain is always included
if 'uni-find-api.onrender.com' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('uni-find-api.onrender.com')

# Add Codespaces domains
ALLOWED_HOSTS.extend([
    'symmetrical-doodle-5w7q67grxj37j7-8000.app.github.dev',
    '*.app.github.dev',
])

# CSRF trusted origins for development
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:9002',
    'http://127.0.0.1:9002',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://symmetrical-doodle-5w7q67grxj37j7-9002.app.github.dev',

]

# Trust the 'X-Forwarded-Proto' header from the reverse proxy (like Render)
# This ensures request.build_absolute_uri() generates https:// URLs correctly.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# allow frontend to access backend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",
    "http://localhost:5173",
    "http://localhost:4173", # LOCAL BUILD
    "http://localhost:9002", # Vite healthcare frontend
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

     'corsheaders',
     'django_filters',

     'djoser',
     'rest_framework.authtoken',
     'rest_framework_simplejwt',
     
     'authentication',
     'healthcare',  # Healthcare app
]

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
     'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'university_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'university_api.wsgi.application'

# Set MEDIA_ROOT to the mount path of your persistent disk
MEDIA_ROOT = os.path.join('/var/data', 'media')
MEDIA_URL = '/media/'

# The persistent disk is not available during the build. To avoid build errors
# caused by a missing directory, disable file storage checks during the build
# phase. Use an environment variable like IS_RENDER_BUILD to control this.
if not os.getenv('IS_RENDER_BUILD'):
    # Configure your media file storage settings here
    pass


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration - use PostgreSQL for both local and production
if 'DATABASE_URL' in os.environ:
    # Production (Render) or local with DATABASE_URL
    print(f"Using DATABASE_URL: {os.environ.get('DATABASE_URL', 'Not set')[:50]}...")
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            ssl_require=True if not DEBUG else False
        )
    }
else:
    # Local development fallback to SQLite (but PostgreSQL recommended)
    print("WARNING: Using SQLite locally. For production parity, use PostgreSQL with DATABASE_URL")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Deployment on Render

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# media definition

# ... at the end of settings.py

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#NOTIFICATION AND ASYNC TASKS SETTINGS

# Email Configuration
# Use Gmail SMTP for both development and production
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'addistemari.m@gmail.com'
EMAIL_HOST_PASSWORD = 'nmfs wzua fryu mtks'
DEFAULT_FROM_EMAIL = 'addistemari.m@gmail.com'
EMAIL_USE_SSL = False
EMAIL_TIMEOUT = 30


# Celery Configuration
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat (for scheduled tasks)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_SCHEDULE = {
    'check-subscription-expiry-every-day': {
        'task': 'profiles.tasks.check_subscription_expirations',
        'schedule': 86400.0,  # Run once every 24 hours (in seconds)
    },
}

# ScholarshipOwl API Configuration
SCHOLARSHIPOWL_API_KEY = os.environ.get('SCHOLARSHIPOWL_API_KEY')

# Custom User Model
AUTH_USER_MODEL = 'authentication.User'