# Generated by Django 5.2.5 on 2025-12-03 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_add_card_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('vaccine_type', models.CharField(max_length=100)),
                ('dose_number', models.PositiveIntegerField(help_text='Which dose in the series (1, 2, 3, etc.)')),
                ('total_doses_required', models.PositiveIntegerField(default=1)),
                ('administered_date', models.DateField()),
                ('administration_site', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('lot_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('next_dose_due', models.DateField(blank=True, null=True)),
                ('adverse_reaction', models.BooleanField(default=False)),
                ('reaction_details', models.TextField(blank=True, null=True)),
                ('vaccine_certificate_generated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-administered_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('intramuscular', 'Intramuscular (IM)'), ('intravenous', 'Intravenous (IV)'), ('subcutaneous', 'Subcutaneous (SC)'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('rectal', 'Rectal'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('administered', 'Administered'), ('refused', 'Refused'), ('held', 'Held'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('scheduled_time', models.DateTimeField()),
                ('administered_time', models.DateTimeField(blank=True, null=True)),
                ('injection_site', models.CharField(blank=True, max_length=100, null=True)),
                ('iv_line_location', models.CharField(blank=True, max_length=100, null=True)),
                ('flow_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('patient_response', models.TextField(blank=True, null=True)),
                ('adverse_reaction', models.BooleanField(default=False)),
                ('adverse_reaction_details', models.TextField(blank=True, null=True)),
                ('requires_observation', models.BooleanField(default=False)),
                ('observation_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('observation_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-administered_time', '-scheduled_time'],
            },
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='healthcare__card_nu_878a82_idx',
            old_name='healthcare_p_card_nu_idx',
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_number',
            field=models.CharField(blank=True, help_text='Unique prescription identifier (RX-001, RX-002, etc.)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='immunization',
            name='administered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_immunizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='immunization',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='healthcare.patient'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='administered_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['nurse', 'triage', 'doctor', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='ordered_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='healthcare.patient'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_medications', to='healthcare.visit'),
        ),
    ]
