# Generated by Django 5.2.5 on 2025-12-03 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_add_prescription_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['stage'], name='healthcare__stage_78d175_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['check_in_time'], name='healthcare__check_i_ae21a3_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['stage', 'check_in_time'], name='healthcare__stage_538238_idx'),
        ),
    ]
